// Package output handles writing AI task results to disk.
package output

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/thecoolrobot/task-agent/internal/ai"
	"github.com/thecoolrobot/task-agent/internal/asana"
)

var safeName = regexp.MustCompile(`[^a-zA-Z0-9\-_. ]`)

func sanitize(name string) string {
	safe := safeName.ReplaceAllString(name, "_")
	safe = strings.TrimSpace(safe)
	safe = strings.ReplaceAll(safe, " ", "_")
	if len(safe) > 60 {
		safe = safe[:60]
	}
	return safe
}

// Write saves an AI TaskResult to disk and returns the output folder path.
func Write(result *ai.TaskResult, task *asana.Task, outputDir string) (string, error) {
	timestamp := time.Now().Format("20060102_150405")
	folderName := fmt.Sprintf("%s_%s", timestamp, sanitize(task.Name))
	outPath := filepath.Join(outputDir, folderName)

	if err := os.MkdirAll(outPath, 0755); err != nil {
		return "", fmt.Errorf("create output dir: %w", err)
	}

	// Write each file
	for _, f := range result.Files {
		filePath := filepath.Join(outPath, filepath.FromSlash(f.Path))
		if err := os.MkdirAll(filepath.Dir(filePath), 0755); err != nil {
			return "", fmt.Errorf("create dir for %s: %w", f.Path, err)
		}
		if err := os.WriteFile(filePath, []byte(f.Content), 0644); err != nil {
			return "", fmt.Errorf("write %s: %w", f.Path, err)
		}
	}

	// Write manifest
	manifest := buildManifest(result, task)
	manifestPath := filepath.Join(outPath, "AGENT_MANIFEST.md")
	if err := os.WriteFile(manifestPath, []byte(manifest), 0644); err != nil {
		return "", fmt.Errorf("write manifest: %w", err)
	}

	return outPath, nil
}

func buildManifest(result *ai.TaskResult, task *asana.Task) string {
	var b strings.Builder
	now := time.Now().Format("2006-01-02 15:04:05")

	fmt.Fprintf(&b, "# 🤖 Task Agent Output\n\n")
	fmt.Fprintf(&b, "| Field | Value |\n|-------|-------|\n")
	fmt.Fprintf(&b, "| **Task** | %s |\n", task.Name)
	fmt.Fprintf(&b, "| **Task ID** | `%s` |\n", task.GetID())
	fmt.Fprintf(&b, "| **Generated** | %s |\n", now)
	fmt.Fprintf(&b, "| **Output Type** | %s |\n\n", result.OutputType)

	fmt.Fprintf(&b, "## Summary\n\n%s\n\n", result.Summary)

	fmt.Fprintf(&b, "## Files Generated\n\n")
	for _, f := range result.Files {
		fmt.Fprintf(&b, "- **`%s`** — %s\n", f.Path, f.Description)
	}

	if result.Notes != "" {
		fmt.Fprintf(&b, "\n## Agent Notes\n\n%s\n", result.Notes)
	}

	fmt.Fprintf(&b, "\n---\n*Generated by task-agent YOLO mode*\n")
	return b.String()
}

// Preview returns a short preview string for display in the TUI.
func Preview(result *ai.TaskResult) string {
	var b strings.Builder
	fmt.Fprintf(&b, "📋 %s\n\n", result.Summary)
	for _, f := range result.Files {
		fmt.Fprintf(&b, "  📄 %s — %s\n", f.Path, f.Description)
	}
	if result.Notes != "" {
		fmt.Fprintf(&b, "\n📝 %s\n", result.Notes)
	}
	return b.String()
}
